### ISSUE TITLE
Copy

### ISSUE THREAD

**Issue by 098765432109876543211234567890** [An-prog-hub/Adobe_Photoshop_Clone#1]
I think you copied from another respitory

**Comment by An-prog-hub** [comment]
I make this project by taking help by web dev simplified tutorial which he post on youtube @098765432109876543211234567890

**Comment by An-prog-hub** [comment]
Please close this issue if you want!

**Comment by 098765432109876543211234567890** [comment]
Ah, ok, just wasn't sure
